//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPARTO_APP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDO_PRODUCTO = new HashSet<PEDIDO_PRODUCTO>();
        }
    
        public int ID_PEDIDO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_UBICACION { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> CANTIDAD_ITEM { get; set; }
        public Nullable<int> VALOR_TOTAL { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual UBICACION UBICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_PRODUCTO> PEDIDO_PRODUCTO { get; set; }
    }
}
