//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPARTO_APP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PRODUCTO
    {
        public int ID_PEDIDO_PRODUCTO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
