//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPARTO_APP_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBICACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UBICACION()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_UBICACION { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_REGION { get; set; }
        public Nullable<int> ID_PROVINCIA { get; set; }
        public Nullable<int> ID_COMUNA { get; set; }
        public Nullable<int> CALLE { get; set; }
        public string NUMERO { get; set; }
        public string TIPO_VIVIENDA { get; set; }
        public Nullable<int> NRO_DEPTO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual REGION REGION { get; set; }
    }
}
